### ISSUE TITLE
that doesn't exist (increase daily song query limit on YT)

### ISSUE THREAD

**Issue by Defarus** [codetheweb/muse#315]
Hey! I've been enjoying the bot you've made and it worked near flawlessly for a few song searches before completely stopping top result searches. It will only respond with "that doesn't exist".

I've tried for an hour or two now with various restarts / reimplementations but haven't been able to replicate my initial success with the searches. I believe the issue lies with pulls from Youtube that aren't a direct link, as Spotify playlists have also stopped being played, even when it adds them to the queue.

Do you have any ideas on how I could go about fixing this? There's a good chance something just flew over my head, but I'm curious as to where I would've went wrong as well! Thanks!

**Comment by hammondses** [comment]
I'm trying to get it setup for the first time and I'm facing the same problems. None of the services seem to give me anything other than 'that doesn't exist'

**Comment by codetheweb** [comment]
YouTube's API comes with [10,000 credits per day](https://developers.google.com/youtube/v3/guides/quota_and_compliance_audits). Doing a YouTube search consumes 100 credits, so you're effectively limited to 100 searches per day. The only way to increase this limit is to contact Google and ask nicely, but seeing as how their form asks for business details that avenue seems unlikely.

There's not really any good solution to this (although the error definitely could be improved). I could implement some kind of API key rotation scheme so you could double or triple your daily credits, but I'm guessing Google wouldn't be too happy with that. 
I used to use [ytsr](https://github.com/TimeForANinja/node-ytsr/tree/cc27f838e504c50e1ac14812b501f18d0e8bc11f) which scrapes the results page instead of making an API call and so doesn't require an API key / has much higher limits (in theory). However it kept breaking whenever a small change to YouTube's site was made and so I moved to their official API.

I think the best way forward might be to do a few things:
- Make error more descriptive of what the actual issue is (hit API limit)
- Use YouTube API if credits left in daily quota, otherwise fallback to `ytsr` knowing that it may not be as reliable

I probably won't get to this until this weekend, happy to accept PRs in the meantime. :)

**Comment by Defarus** [comment]
That makes sense and I appreciate the information. I think a slightly more descriptive error for that would be helpful but it's entirely understandable why it's not there already. You're great - thanks and have an awesome night!

**Comment by cheqpat** [comment]
Testing this on my end and I have the same issue. Youtube API claim it has only received 12 requests, yet all commands that aren't a youtube link now result in a ":no_entry_sign: that doesn't exist" message.
This is slightly confusing as Spotify links don't work at all, and the Spotify dashboard claims no traffic has come through (I don't know how to test if this is due to the previous issue or it being set up wrong on my end though).

**Comment by luisfavila** [comment]
Same thing here, both youtube search and spotify links return `no songs found`. Is the spotify bit also related to the Google API limits (Search hasn't worked a single time so it's weird for it to have hit any limits)?

**Comment by ssMMiles** [comment]
`this.youtubeVideo()` expects a URL, not a video ID. I submitted #321 as an easy fix for now, but ytsr is easy to swap in.

**Comment by codetheweb** [comment]
I think @cheqpat @luisfavila @ssMMiles your issues were caused by a regression that should now be fixed, please let me know if you continue to get this error.

(This issue specifically is about upping the limit of song requests / day, so if your problem is unrelated to that please open a new issue.)

**Comment by tymondouglas** [comment]
I'm getting the error too.
First time setup.
I've checked the GCP and it received the requests, but with 100% ERROR

**Comment by codetheweb** [comment]
@tymondouglas are you saying that GCP reports that all requests errored or Muse is throwing errors? Please open a new issue with additional issues if you still need help.

**Comment by codetheweb** [comment]
This should be now fixed.

A few notes:
- ytsr is now used for all search queries, not just after credits run out. This makes more sense as the official YT API is still necessary to resolve playlists and get video details (operations that consume credits)
- I took the opportunity to throw in a caching system, so adding tracks multiple times within an hour should be ultra fast now. ⚡ 
	- Most operations are cached for 1 hour, playlist resolving is cached for 1 minute. Happy to change this based on feedback, could also add a command to manually evict the cache.
