### ISSUE TITLE
Migrate to Prisma

### ISSUE THREAD

**Issue by codetheweb** [codetheweb/muse#426]
[Prisma](https://www.prisma.io/) has first-class support for TypeScript and migrations are much nicer than Sequelize.

**Comment by pondpiu** [comment]
I've take a look into this and found some possible issues
1. Datasource url
Prisma looks for db url at schema.prisma in form of 
```
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}
```
Existing sqlite file is located at `path.join(DATA_DIR, 'db.sqlite')`
as of now schema.prisma file does not support string concatination, 
current workaround rely on dotenv-expand and would need additional env like so 
`DATABASE_URL=file:${DATA_DIR}/db.sqlite`
Ref: https://github.com/prisma/prisma/issues/2559

2. Retaining existing data
In order for prisma migrate to work properly, a full migration history is needed.
We can use prisma introspect to pull schema, but to retain existing data,
existing user would need to run `prisma migrate resolve` once to baseline a migration history but new user must not run it.
Ref: https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/add-prisma-migrate-to-a-project#baseline-your-production-environment

Work around that i can come up with is to create 1 empty migration which EVERYONE would baseline to, and another migration with command that is safe to run for both group (ie, IF NOT EXIST)

3. String Data type
`String` data type in prisma schema would result in `TEXT` type in SQLite rather than `VARCHAR(255)`

What do you think about these?

**Comment by codetheweb** [comment]
Thanks for investigating.

1. I would rather not include additional env files in the repo, that feels a little messy. What could work instead is modifying the `start` script in `package.json` to something like `DATABASE_URL=$(DATA_DIR)/db.sqlite node ....` (obviously that would need to be modified so that it works on both Windows and *nix, but I think something like that would be fine.)
2. Probably easiest to create a small script that detects if user currently has data / was formally using Sequelize and then spawn the Prisma CLI to migrate as necessary (again, adding this to `yarn start` in some form). Prisma's main downside for our use case is that it doesn't currently have programmatic migrations, so we'd probably want to keep this script around (assuming we want migrations to be applied automatically upon `yarn start`).
3. As long as this doesn't mess up migrations, I don't this that's an issue.
