### ISSUE TITLE
Inconsistent column data error when using play query command

### ISSUE THREAD

**Issue by AaronWiora** [codetheweb/muse#503]
Maybe im doing it wrong because it's the first time ever I've used slash commands but when Im trying to play a song I get an error message.

`.play query https://www.youtube.com/watch?v=WrsFXgQk5UI`
`.play query Lil Uzi Vert - XO Tour Llif3`

**Error Message**
`🚫 ope: Inconsistent column data: Could not convert value "playlistLimit" of the field playlistLimit to type Int.`

**Comment by codetheweb** [comment]
Looks like some of the database migrations might have failed.

If you don't care about any data Muse might have stored, you can 
1. Stop Muse
2. Delete `db.sqlite` in the data directory
3. Start Muse
4. Kick & re-add Muse

Otherwise you might need to edit the database manually to change the column type of `playlistLimit`.

**Comment by AaronWiora** [comment]
I did not care about any data so I went with deleting the SQLite file and it worked.
Because it would throw an error at starting up (Step 3) I had to kick the bot before using docker-compose up.
