### ISSUE TITLE
Remove spotify

### ISSUE THREAD

**Issue by MattJGH** [codetheweb/muse#537]
Is there a way to just do /play test or /play youtube URL, so the bot just uses youtube, instead of /play query test. Thanks!

**Comment by codetheweb** [comment]
Are you asking if there's a way to mark `query` as the default parameter to reduce the number of keystrokes required? Unfortunately not that I'm aware.

**Comment by Hellysonrp** [comment]
I modified this behavior for my instance of the bot.
Personally I find it easier to use if `query` is required.
My solution was to create a separate command to `resume` the playback and remove this functionality from the `play` command.
Since this is a change based on my own opinions, I didn't open a PR, but [you can find the changes in one of my branches](https://github.com/Hellysonrp/muse/tree/add-resume-command).

**Comment by codetheweb** [comment]
@Hellysonrp I actually like that, would be happy to accept a PR. :)
