### ISSUE TITLE
Update youtube.ts

### ISSUE THREAD

**Issue by c-schuhmann** [codetheweb/muse#899]
It seems that the package youtube.ts contains a vastly outdated version of axios (and other older dependencies), which contains a high vulnerability. The original repository seems to be archived.

I created a fork where I replaced Axios with node-fetch and updated several other dependencies. I saw that you also have a fork of youtube.ts. If the changes I did in my fork are okay for you, you can integrate these into your own fork. Then you could integrate your own version/package of youtube.ts without the vulnerability.

**Comment by codetheweb** [comment]
The probability of those types of vulnerabilities being exploited seems extremely low. 😅 

I'd rather replace `youtube.ts` entirely at this point. I don't see any up-to-date packages that have typings, so might be easiest to just use axios directly and define our own types instead of having a separate package.

**Comment by c-schuhmann** [comment]
Understandable 👍 I can try to create a PR for this.
